name: Run Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  test-playwright:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.6

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests TC01
        run: npm run test:tc01
        env:
          WEBAPP_URL: ${{ vars.WEBAPP_URL }}

      - name: Deploy Report for TC01
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: playwright-report
          target-folder: tests/tc-01/

      - name: Run Playwright tests TC04
        run: npm run test:tc04
        env:
          WEBAPP_URL: ${{  vars.WEBAPP_URL }}

      - name: Deploy Report for TC04
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: playwright-report
          target-folder: tests/tc-04/
